title: Ayorinde Amao
logo: /assets/img/logo.png
description: I am a data analyst with deep experience in analyzing data using advanced excel for report automation,
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
